* standard-keys-mode

standard-keys-mode is yet another cua-mode that try to emulate the
standard and common keybindings from modern editors.

This package is intended for people who don't like the default Emacs
keybindings; as a good starting point for refugees from other text
editors; or for people who want to rebind the classic ~C-x/C-c~ key
prefixes.

** Installation and Usage

~standard-keys-mode~ is not available in any ELPA, but you can install it
using ~package-vc-install~:

=M-x package-vc-install RET https://github.com/DevelopmentCool2449/standard-keys-mode RET=

Alternatively using ~use-package~ ~:vc~ keyword:

#+begin_src emacs-lisp
(use-package standard-keys-mode
  :ensure t
  :vc ( :url "https://github.com/DevelopmentCool2449/standard-keys-mode"
        :rev :newest))
#+end_src

Once you have it installed you can enable it with =M-x standard-keys-mode=

Example configuration:

#+begin_src emacs-lisp
(use-package standard-keys-mode
  :ensure t
  :custom (standard-keys-override-C-x-and-C-c-commands t)
  :bind (:map standard-keys-default-keymap
              ("C-t" . tab-line-new-tab))
  :hook after-init)
#+end_src

** Keybindings

~standard-keys-mode~ includes the following additional keymaps
out-the-box:

+ ~standard-keys-default-keymap~
  Default keymap used in ~standard-keys-map-style~.

+ ~standard-keys-ergoemacs-like-keymap~
  Ergoemacs-like keymap.
  This keymap emulates the ~Ergoemacs US layout Standard~ from ~ergoemacs-mode~.
  *It is not a complete emulation*, it just provides some basic
  keybindings from ergoemacs.

+ ~standard-keys-minimal-keymap~
  A minimal keymap, which binding only a few keybindings in cua-style.

standard-keys uses ~standard-keys-default-keymap~ by default, which
defines the following keybindings:

| key                  | command                                                             |
|----------------------+---------------------------------------------------------------------|
| =Control= =o=            | =find-file= (Open file)                                               |
| =Control= =Shift= =o=      | =revert-buffer= (Refresh/Update current buffer file state)            |
| =Control= =w=            | =kill-current-buffer= (Quit/Kill current buffer)                      |
| =Control= =q=            | =save-buffers-kill-terminal= (Quit Emacs)                             |
| =Control= =e=            | =C-x= prefix                                                          |
| =Control= =d=            | =C-c= prefix                                                          |
| =Control= =x=            | =kill-region= (Cut)                                                   |
| =Control= =c=            | =kill-ring-save= (Copy)                                               |
| =Control= =v=            | =yank= (Paste)                                                        |
| =Control= =z=            | =undo=                                                                |
| =Control= =y=            | =undo-redo= (Redo)                                                    |
| =Control= =Shift= =z=      | =undo-redo= (Redo)                                                    |
| =Control= =f=            | =isearch-forward=  (Search forward)                                   |
| =Control= =Shift= =f=      | =isearch-backward= (Search backward)                                  |
| =Control= =r=            | =query-replace= (Replace)                                             |
| =Control= =Shift= =r=      | =query-replace-regexp= (Replace with regexp)                          |
| =Control= =s=            | =save-buffer= (Save buffer/file)                                      |
| =Control= =Shift= =s=      | =write-file= (Save buffer/file as)                                    |
| =Control= =p=            | =print-buffer= (Print buffer/file)                                    |
| =Control= =a=            | =mark-whole-buffer= (Select All)                                      |
| =Control= =+=            | =text-scale-increase= (Zoom in)                                       |
| =Control= =-=            | =text-scale-decrease= (Zoom out)                                      |
| =Control= ~=~            | =text-scale-adjust= (Set Zoom)                                        |
| =Control= =;=            | =comment-line= (Comment out current line)                             |
| =Alt/Meta= =1=           | =delete-other-windows=                                                |
| =Alt/Meta= =2=           | =split-window-below=                                                  |
| =Alt/Meta= =3=           | =split-window-right=                                                  |
| =Control= =RETURN=       | =rectangle-mark-mode= (Select in rectangle mode)                      |
| =Control= =Shift= =RETURN= | =sk-newline-and-indent-before-point= (Insert a newline before cursor) |
| =Control= =b=            | =switch-to-buffer=                                                    |
| =HOME=                 | =sk-move-beginning-of-line-or-indentation=                            |
| =ESC=                  | =sk-keyboard-quit= (Cancel current action, similar to C-g)            |

*** Change the keymap to use
To change the keymap to use, change ~standard-keys-map-style~ value to
the keymap style you want to use.
#+begin_src emacs-lisp
(setopt standard-keys-map-style 'keymap-to-use)

;; or if you prefer to use `use-package'...
:custom (standard-keys-map-style 'keymap-to-use)
#+end_src

*** Change the keymaps keybindings
To change the keymap keybindings is simple, if you are using the
default keymap set in ~standard-keys-map-style~, change the keybindings
defined in that keymap (~standard-keys-default-keymap~).

#+begin_src emacs-lisp
(keymap-set standard-keys-default-keymap "C-t" #'tab-line-new-tab)

;; or with `use-package'
:bind (:map standard-keys-default-keymap
            ("C-t" . tab-line-new-tab))
#+end_src

** User options
+ ~standard-keys-update-commands-descriptions~

  If non-nil, commands docstring descriptions should use the
  remaped ~C-x~ and ~C-c~.

  This only have effect if ~standard-keys-update-commands-descriptions~
  is non-nil.

  default: =t=

+ ~standard-keys-C-x-prefix-for-descriptions~

  The key where C-x is remaped and use it for the commands
  descriptions.

  This only have effect if ~standard-keys-update-commands-descriptions~
  is non-nil.

  default: =?\C-e=

+ ~standard-keys-C-c-prefix-for-descriptions~

  The key where C-c is remaped and use it for the commands
  descriptions.

  This only have effect if ~standard-keys-update-commands-descriptions~
  is non-nil.

  default: =?\C-d=

+ ~standard-keys-override-new-C-x-and-C-c-commands~

  If non-nil, commands bounds in =C-x= and =C-c= must take precedence over other keymaps.

  WARNING: This only should be used only for override the =C-x= and =C-c=
  only in buffers or modes which take precedence over
  ~standard-keys-map~.

  Intended to be used for copy/cut text in magit buffers or in URLs
  with ~goto-address-mode~ enabled.

  default: =nil=

+ ~standard-keys-map-style~

  The keymap style to use.

  Use this option to change the default keymap to use.

  default: =standard-keys-default-keymap=

** Troubleshooting
+ The copy and cut commands (C-c, C-x) doesn't work well in magit or with goto-address-mode.

  This is a common bug, ~standard-keys-mode~ provides the variable
  ~standard-keys-override-C-x-and-C-c-commands~ as workaround, which is
  disabled by default, you can set it to =t= for enable this.

+ The menu-bar command keybinding description is not updated.

  Currently there is not a possible workaround, but as an alternative,
  the =marginalia= package provides detailed information about the
  commands keybindings.

** Roadmap
+ Add more keyboard and keybindings themes/templates keymaps.

#+begin_quote
e.g.
more keymaps for dvorak/colemak keyboards
and keymaps that includes keybindings from other editors
(such as VSCode, notepad)
#+end_quote

** Alternatives

+ [[http://ergoemacs.github.io/][ergoemacs]].
#+begin_quote
A minor-mode that aims to:
- Use/Create ergonomic keybindings in emacs that will reduce RSI
- Use the commonly bound keys familiar to most people today. Ctrl+C
  for copy, Ctrl+z for undo, etc.
#+end_quote
    
ergoemacs is very opinated, from my experience, it is hard to
customize and use, and documentation is very outdated.

But if you don't care about this, you can try it.
  
+ [[https://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html][cua-mode]] (built-in in Emacs).
#+begin_quote
CUA mode is a global minor mode.  When enabled, typed text
replaces the active selection, and you can use C-z, C-x, C-c, and
C-v to undo, cut, copy, and paste in addition to the normal Emacs
bindings.  The C-x and C-c keys only do cut and copy when the
region is active, so in most cases, they do not conflict with the
normal function of these prefix keys.
#+end_quote

cua-mode doesn't include the classic commands that you may expect:
C-o (Open), C-s (Save), C-f (Search), etc; so you will probably have
to invest time in configuring it.

However cua-mode mode includes some features you may be interested in
(e.g. =cua-enable-cursor-indications=, =cua-toggle-rectangle-mark=, etc).

+ [[https://github.com/darkstego/wakib-keys][wakib-keys]]
#+begin_quote
Emacs minor mode that provides a modern, efficient and easy to learn
keybindings.  This mode makes it easy to pick up Emacs and start
unlocking its potential without having to sacrifice its power. The
point of this mode it to leverage common shortcuts that you are used
to while making it easy to learn Emacs.
#+end_quote

wakib-keys was the inspiration for package.

Like standard-keys-mode, wakib rebinds the C-x/C-c prefixes to C-e/C-d
respectively.  However wakib has been somewhat outdated, with some
unfixed bugs, and it does not work properly on recent versions of
Emacs.

If you are using an older Emacs version (prior 29.1), you can use
wakib-keys instead of standard-keys-mode.

-----
Thanks to Abdulla Bubshait (darkstego) for creating wakib-keys, which
was the inspiration for this package.
